apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-serving
  labels:
    app: ml-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-serving
  template:
    metadata:
      labels:
        app: ml-serving
    spec:
      containers:
        - name: app
          image: ml-serving-app  # Replace with your Docker Hub image if pushing
          ports:
            - containerPort: 80
